/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    Aside: typeof import('./src/components/Aside.vue')['default']
    AsideButton: typeof import('./src/components/atoms/AsideButton.vue')['default']
    Avatar: typeof import('./src/components/atoms/Avatar.vue')['default']
    Divider: typeof import('./src/components/atoms/Divider.vue')['default']
    DynamicIcon: typeof import('./src/components/atoms/icons/DynamicIcon.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Header: typeof import('./src/components/Header.vue')['default']
    HistoryIcon: typeof import('./src/components/atoms/icons/HistoryIcon.vue')['default']
    HomeIcon: typeof import('./src/components/atoms/icons/HomeIcon.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    LoginQRCode: typeof import('./src/components/molecules/LoginQRCode.vue')['default']
    MainLayouts: typeof import('./src/layouts/MainLayouts.vue')['default']
    Popover: typeof import('@headlessui/vue')['Popover']
    PopoverButton: typeof import('@headlessui/vue')['PopoverButton']
    PopoverOverlay: typeof import('@headlessui/vue')['PopoverOverlay']
    PopoverPanel: typeof import('@headlessui/vue')['PopoverPanel']
    PopularIcon: typeof import('./src/components/atoms/icons/PopularIcon.vue')['default']
    PopularView: typeof import('./src/views/PopularView.vue')['default']
    Progress: typeof import('./src/components/atoms/Progress.vue')['default']
    RcmdView: typeof import('./src/views/RcmdView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowQRCode: typeof import('./src/components/atoms/ShowQRCode.vue')['default']
    UserAvatar: typeof import('./src/components/molecules/UserAvatar.vue')['default']
    UserInfoBox: typeof import('./src/components/atoms/UserInfoBox.vue')['default']
    UserMenu: typeof import('./src/components/UserMenu.vue')['default']
    VideosView: typeof import('./src/views/VideosView.vue')['default']
  }
}
